# Generated by Django 3.2.13 on 2022-11-02 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20221102_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='hits',
            field=models.PositiveIntegerField(default=1, verbose_name='조회수'),
        ),
    ]
