# Generated by Django 3.2.13 on 2022-11-02 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20221102_1025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='tag_content',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='article',
            name='tagging',
        ),
    ]
