# Generated by Django 3.2.13 on 2022-11-02 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20221102_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='modify_dt',
            field=models.DateTimeField(auto_now=True, verbose_name='MODIFY DATE'),
        ),
    ]
