# Generated by Django 3.2.13 on 2022-11-02 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_alter_article_hits'),
        ('articles', '0007_article_modify_dt'),
    ]

    operations = [
    ]
