# Generated by Django 3.2.13 on 2022-11-03 02:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0009_auto_20221102_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='bookmark_users',
            field=models.ManyToManyField(related_name='bookmark_articles', to=settings.AUTH_USER_MODEL),
        ),
    ]
