# Generated by Django 3.2.13 on 2022-11-03 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_alter_comment_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comment',
            table=None,
        ),
    ]
