# Generated by Django 3.2.13 on 2022-11-04 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_alter_comment_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='location',
            field=models.CharField(choices=[('서울', '서울'), ('인천', '인천'), ('제주도', '제주도'), ('경기도', '경기도'), ('강원도', '강원도'), ('경상도', '경상도'), ('충청도', '충청도'), ('전라도', '전라도')], default=True, max_length=80),
        ),
    ]
