# Generated by Django 3.2.13 on 2022-11-04 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0015_article_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='location',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
