# Generated by Django 3.2.13 on 2022-11-04 02:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='movie_name',
        ),
        migrations.AddField(
            model_name='comments',
            name='like_users',
            field=models.ManyToManyField(related_name='like_comment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comments',
            name='parent_comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='community.comments'),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='community.articles')),
            ],
        ),
    ]
